$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Monitoring Performace
jobs:
  hello_job:
      command: echo "hello" && echo "world" > ${{outputs.world_output}}/world.txt
      environment: azureml:TestNew@latest
      compute: azureml:GPU-05559-01
      outputs:
        world_output:
  monitoring:
    type: command
    code: generateData
    environment: azureml:TestNew@latest
    compute: azureml:GPU-05559-01
    command: >-
      python monitoring.py

