$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Model Deployment to Elastic
jobs:
  huggingface:
    type: command
    code: huggingface
    inputs:
      prepped_data: "data"
    outputs:
      status_output:
        mode: upload
    environment: azureml:ModelTraining@latest
    compute: azureml:GPU002
    command: >-
      python huggingface.py 
      --prepped_data ${{inputs.prepped_data}}
      --status_output ${{outputs.status_output}}      
