$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Model Deployment to Elastic
jobs:
  elastic:
    type: command
    code: elastic
    environment: azureml:ElandRequirments@latest
    compute: azureml:GPU002
    command: >-
      python eland_import_hub_model2.py                                                           
      --hub-model-id yashveer11/final_model_category
      --url https://49a88e589a0a4bad9350451ebeae8797.es.eastus2.azure.elastic-cloud.com:9243/
      --task-type text_classification
      --es-api-key Y2FYbkxZZ0I2dGg1ZG05ZEw2S1A6SjMxR2dnWGZURHVlREpzT1FrZVp1QQ==
      --clear-previous
      --start
