$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Model Deployment to Elastic
jobs:
  elastic:
    type: command
    code: elastic
    environment: azureml:ElandRequirments@latest
    compute: azureml:GPU002
    command: >-
      python eland_import_hub_model.py      
      --url https://49a88e589a0a4bad9350451ebeae8797.es.eastus2.azure.elastic-cloud.com:9243/                                                     
      --hub-model-id yashveer11/final_model_category
      --task-type text_classification
      --es-api-key MEowRjhJY0I2dGg1ZG05ZHloNDU6Qmc5ZnJxVUxTRTZEcVBRNjFZa1d6QQ==
      --cloud-id Elastic-05559-s-001:ZWFzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo0NDMkNDlhODhlNTg5YTBhNGJhZDkzNTA0NTFlYmVhZTg3OTckMDdlYjU1NzhjODdlNGI3MWI5NmIwNjY0ZmY3NWI4ODc=
      --clear-previous
      --start
