$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: Model Deployment to Elastic
jobs:
  read_data:
    type: command
    outputs:
      fetched_data: 
        mode: upload
    code: data
    environment: azureml:ModelTraining@latest
    compute: azureml:GPU-05559-01
    command: >-
      python read_data.py 
      --fetched_data ${{outputs.fetched_data}}
      
  preprocess_data:
    type: command
    inputs:
      real_data: ${{parent.jobs.read_data.outputs.fetched_data}}
    outputs:
      transformed_data: 
        mode: upload
    code: prepare_data
    environment: azureml:ModelTraining@latest
    compute: azureml:GPU-05559-01
    command: >-
      python preprocessing.py 
      --real_data ${{inputs.real_data}}
      --transformed_data ${{outputs.transformed_data}}

  huggingface:
    type: command
    code: huggingface
    inputs:
      prepped_data: ${{parent.jobs.preprocess_data.outputs.transformed_data}}
    outputs:
      status_output:
        mode: upload
    environment: azureml:ModelTraining@latest
    compute: azureml:GPU-05559-01
    command: >- 
      python huggingface.py 
      --prepped_data ${{inputs.prepped_data}}
      --status_output ${{outputs.status_output}}
  elastic:
    type: command
    code: elastic
    inputs:
      status_input: ${{parent.jobs.huggingface.outputs.status_output}}
    environment: azureml:ElandRequriments@latest
    compute: azureml:GPU-05559-01
    command: >-
      python eland_import_hub_model.py      
      --cloud-id Elastic-05559-d-002:ZWFzdHVzLmF6dXJlLmVsYXN0aWMtY2xvdWQuY29tOjQ0MyQ0ODVjZTM5MzFmMWU0YjYzOTNmM2EyNTZkOTZiYTc1ZSQ3Njc4ZmQyZjA2NWI0YWM1OTRhYjVlMmVjMTMxYjI3Mw==
      --hub-model-id yashveer11/final_model_category
      --task-type text_classification
      --clear-previous